# Generated by Django 3.0.6 on 2020-05-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.URLField(max_length=400)),
                ('type', models.IntegerField(choices=[(0, 'Dairy product'), (1, 'Vegetable'), (2, 'Fruit'), (3, 'Meat'), (4, 'Flour-like'), (5, 'Rice-like'), (100, 'Unknown')], default=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsOfStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('amount_type', models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('', 'items')], default='', max_length=10)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.URLField(max_length=400)),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Published date')),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Author')),
            ],
        ),
        migrations.CreateModel(
            name='StepsOfRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_amt', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
                ('used_ingredients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.IngredientsOfStep')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientsofstep',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.StepsOfRecipes'),
        ),
    ]
