# Generated by Django 3.0.6 on 2020-05-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200519_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
