# Generated by Django 3.0.6 on 2020-05-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200519_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepsofrecipes',
            name='used_ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredientsofstep',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
        migrations.AlterField(
            model_name='ingredientsofstep',
            name='amount_type',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('x', 'items')], default='x', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
