# Generated by Django 3.0.6 on 2020-05-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200521_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsofstep',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientsofstep',
            old_name='step_id',
            new_name='step',
        ),
        migrations.RenameField(
            model_name='stepsofrecipes',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
